# Generated by Django 5.2.16 on 2026-07-10 05:04

import controller.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='MinerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_key', models.CharField(max_length=150, unique=True)),
                ('display_username', models.CharField(max_length=150)),
                ('is_configured', models.BooleanField(db_index=True, default=True)),
                ('channel_revision', models.PositiveBigIntegerField(default=1)),
                ('configuration_fingerprint', models.CharField(blank=True, max_length=64)),
                ('config_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('config_key',),
            },
        ),
        migrations.CreateModel(
            name='WorkerLease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='miner-supervisor', max_length=100, unique=True)),
                ('owner_id', models.CharField(max_length=200)),
                ('pid', models.PositiveIntegerField(blank=True, null=True)),
                ('acquired_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('heartbeat_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='twitch_farm_actions', to=settings.AUTH_USER_MODEL)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='controller.mineraccount')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='MinerRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_mode', models.CharField(choices=[('default', 'Default channels'), ('custom', 'Custom channels'), ('preset', 'Preset')], max_length=16)),
                ('source_name', models.CharField(blank=True, max_length=150)),
                ('channels', models.JSONField(validators=[controller.models.validate_channel_snapshot])),
                ('configuration_fingerprint', models.CharField(max_length=64)),
                ('channel_revision', models.PositiveBigIntegerField()),
                ('pid', models.PositiveIntegerField(blank=True, null=True)),
                ('worker_id', models.CharField(blank=True, max_length=200)),
                ('startup_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('exit_signal', models.IntegerField(blank=True, null=True)),
                ('stop_reason', models.CharField(blank=True, choices=[('admin_stop', 'Admin stop'), ('config_restart', 'Configuration restart'), ('admin_restart', 'Admin restart'), ('supervisor_shutdown', 'Supervisor shutdown'), ('unexpected_exit', 'Unexpected exit'), ('start_failed', 'Start failed')], max_length=32)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='controller.mineraccount')),
            ],
            options={
                'ordering': ('-started_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='MinerInstanceState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desired_state', models.CharField(choices=[('stopped', 'Stopped'), ('running', 'Running')], db_index=True, default='stopped', max_length=16)),
                ('observed_state', models.CharField(choices=[('starting', 'Starting'), ('running', 'Running'), ('stopping', 'Stopping'), ('stopped', 'Stopped'), ('restarting', 'Restarting'), ('degraded', 'Degraded'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=16)),
                ('advisory_pid', models.PositiveIntegerField(blank=True, null=True)),
                ('worker_id', models.CharField(blank=True, max_length=200)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('stable_since', models.DateTimeField(blank=True, null=True)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='runtime_state', to='controller.mineraccount')),
                ('current_run', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_state', to='controller.minerrun')),
            ],
            options={
                'ordering': ('account__config_key',),
            },
        ),
        migrations.CreateModel(
            name='MinerIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('unexpected_exit', 'Unexpected miner exit'), ('unclean_supervisor', 'Unclean supervisor shutdown')], max_length=32)),
                ('status', models.CharField(choices=[('open', 'Open'), ('recovered', 'Recovered')], db_index=True, default='open', max_length=16)),
                ('summary', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True)),
                ('opened_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('recovered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='controller.mineraccount')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='controller.minerrun')),
            ],
            options={
                'ordering': ('-opened_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='PresetChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.PositiveIntegerField()),
                ('preset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='controller.channelpreset')),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='RestartAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField()),
                ('scheduled_at', models.DateTimeField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('scheduled', 'Scheduled'), ('started', 'Started'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='scheduled', max_length=16)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restart_attempts', to='controller.minerincident')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restart_attempts', to='controller.minerrun')),
            ],
            options={
                'ordering': ('attempt_number', 'id'),
            },
        ),
        migrations.CreateModel(
            name='AccountCustomChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.PositiveIntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_channels', to='controller.mineraccount')),
            ],
            options={
                'ordering': ('position', 'id'),
                'constraints': [models.UniqueConstraint(fields=('account', 'position'), name='controller_unique_custom_channel_position')],
            },
        ),
        migrations.CreateModel(
            name='AccountChannelSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('default', 'Default channels'), ('custom', 'Custom channels'), ('preset', 'Preset')], default='default', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account_selections', to='controller.channelpreset')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='selection', to='controller.mineraccount')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('mode', 'preset'), ('preset__isnull', False)), models.Q(('mode__in', ('default', 'custom')), ('preset__isnull', True)), _connector='OR'), name='controller_selection_mode_matches_preset')],
            },
        ),
        migrations.CreateModel(
            name='MinerCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('start', 'Start'), ('stop', 'Stop'), ('restart', 'Restart')], max_length=16)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('leased', 'Leased'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=16)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('lease_owner', models.CharField(blank=True, max_length=200)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('leased_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='controller.mineraccount')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='miner_commands', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at', 'id'),
                'indexes': [models.Index(fields=['status', 'created_at'], name='ctrl_cmd_status_created_idx'), models.Index(fields=['account', 'status'], name='ctrl_cmd_account_status_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='minerrun',
            index=models.Index(fields=['account', 'ended_at'], name='ctrl_run_account_ended_idx'),
        ),
        migrations.AddConstraint(
            model_name='minerincident',
            constraint=models.UniqueConstraint(condition=models.Q(('account__isnull', False), ('status', 'open')), fields=('account',), name='controller_one_open_incident_per_account'),
        ),
        migrations.AddConstraint(
            model_name='presetchannel',
            constraint=models.UniqueConstraint(fields=('preset', 'position'), name='controller_unique_preset_channel_position'),
        ),
        migrations.AddConstraint(
            model_name='restartattempt',
            constraint=models.UniqueConstraint(fields=('incident', 'attempt_number'), name='controller_unique_restart_attempt_number'),
        ),
    ]
