# Generated by Django 5.2.16 on 2026-07-22 21:43

from django.db import migrations, models
from django.utils import timezone


def preserve_existing_password_accounts(apps, schema_editor):
    AccountCredential = apps.get_model("controller", "AccountCredential")
    MinerInstanceState = apps.get_model("controller", "MinerInstanceState")
    AccountCredential.objects.update(auth_method="legacy_password")
    MinerInstanceState.objects.filter(account__credential__isnull=False).update(
        authentication_status="authenticated",
        authentication_updated_at=timezone.now(),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0002_ui_managed_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountcredential',
            name='auth_method',
            field=models.CharField(choices=[('twitch_tv', 'Twitch TV device login'), ('legacy_password', 'Legacy password')], default='legacy_password', max_length=24),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='minerinstancestate',
            name='authentication_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='minerinstancestate',
            name='authentication_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='minerinstancestate',
            name='authentication_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='minerinstancestate',
            name='authentication_status',
            field=models.CharField(choices=[('unlinked', 'Unlinked'), ('pending', 'Pending'), ('authenticated', 'Authenticated'), ('reauth_required', 'Reauthentication required')], db_index=True, default='unlinked', max_length=24),
        ),
        migrations.AddField(
            model_name='minerinstancestate',
            name='authentication_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='minerinstancestate',
            name='authentication_uri',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='minerrun',
            name='auth_method',
            field=models.CharField(choices=[('twitch_tv', 'Twitch TV device login'), ('legacy_password', 'Legacy password')], default='legacy_password', max_length=24),
        ),
        migrations.AddField(
            model_name='minerrun',
            name='reset_session',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accountcredential',
            name='password_ciphertext',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.RunPython(preserve_existing_password_accounts, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='accountcredential',
            name='auth_method',
            field=models.CharField(choices=[('twitch_tv', 'Twitch TV device login'), ('legacy_password', 'Legacy password')], default='legacy_password', max_length=24),
        ),
        migrations.AlterField(
            model_name='minercommand',
            name='action',
            field=models.CharField(choices=[('start', 'Start'), ('stop', 'Stop'), ('restart', 'Restart'), ('authenticate', 'Authenticate')], max_length=16),
        ),
        migrations.AlterField(
            model_name='minerrun',
            name='stop_reason',
            field=models.CharField(blank=True, choices=[('admin_stop', 'Admin stop'), ('config_restart', 'Configuration restart'), ('admin_restart', 'Admin restart'), ('supervisor_shutdown', 'Supervisor shutdown'), ('unexpected_exit', 'Unexpected exit'), ('start_failed', 'Start failed'), ('authentication_failed', 'Authentication failed'), ('authentication_reset', 'Authentication reset')], max_length=32),
        ),
    ]
