# Generated by Django 6.0.7 on 2026-07-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controller", "0003_accountcredential_auth_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="minerinstancestate",
            name="watching_channels",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="minerinstancestate",
            name="watching_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
