# Generated by Django 6.0.7 on 2026-07-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controller", "0004_minerinstancestate_watching_channels"),
    ]

    operations = [
        migrations.AddField(
            model_name="minerinstancestate",
            name="online_channels",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
